### ISSUE TITLE
Middleware needed for 20.49.0 and Up?

### ISSUE THREAD

**Issue by damclarkd** [rhodesman/teslaPowerDash#29]
While I had this all working before being updated to 20.49.0, I previously had no need for the middleware setup. After being updated to 20.49.0 a few months ago, I am now looking at getting this back up and running again. However I can't seem to get any of the middleware stuff working. Is that part of the setup now required if on 20.49.0 and above?

Cheers,

damclarkd

**Comment by rhodesman** [comment]
Yes, because Tesla has locked down the Powerwall API even for local networks, the middleware is now setup to act as the authentication layer to access the Powerwall API.  

If you need further assistance for getting your middleware up and running, I am happy to assist.  Just ask your questions here and I will do what I can to assist.

**Comment by damclarkd** [comment]
Hello Jason,
Thank you for your assistance in this matter. I have really missed the data since using your original configuration before the Tesla lockdown.

Following your instructions, here is where I am stalling:

After npm start, I get...

> ***@***.*** start
> NODE_TLS_REJECT_UNAUTHORIZED='0' node app.js

Server running at http://10.1.20.45:3301
/home/pi/teslaPowerDash/middleware/api/controllers/appController.js:85
        if (error) throw new Error(error);
                   ^

Error: Error: Invalid URI "/api/login/Basic"
    at Request._callback (/home/pi/teslaPowerDash/middleware/api/controllers/appController.js:85:26)
    at self.callback (/home/pi/teslaPowerDash/middleware/node_modules/request/request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.init (/home/pi/teslaPowerDash/middleware/node_modules/request/request.js:273:17)
    at new Request (/home/pi/teslaPowerDash/middleware/node_modules/request/request.js:127:8)
    at request (/home/pi/teslaPowerDash/middleware/node_modules/request/index.js:53:10)
    at /home/pi/teslaPowerDash/middleware/api/controllers/appController.js:84:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)


Cannot connect to http://10.1.20.45:3301 <http://10.1.20.45:3301/> in a browser.

Any thoughts?

Cheers,

**Comment by persson** [comment]
With a first time setup, with 2.49.0, I got an auth error when calling the middleware api for any endpoint except `api/site_info`.  The error seems similar to:
https://github.com/vloschiavo/powerwall2/issues/41#issuecomment-773456210

Comparing the auth header sent by middleware with a browser session, I decided to change the middleware to use a cookie jar instead.   It has been working for the last few days.  But it is not well tested, so not PR ready, but worked for me.

Patch file:
[cookie_jar.patch.gz](https://github.com/rhodesman/teslaPowerDash/files/6869633/cookie_jar.patch.gz)

**Comment by damclarkd** [comment]
Hello Erik,
What is the proper way to implement the patch files?

Cheers,

**Comment by persson** [comment]
https://google.com/search?q=git+patch

JK... kinda.
Something like:

- Checkout this git repo
- Download and unzip patch file
- `cd` to middleware sub-directory in checked out git code
- `git apply /path/to/unzipped_patch_file.patchfile`
- If no errors from `git apply` you can review what changed (should look just like patch file) with `git status` and `git diff`.

**Comment by damclarkd** [comment]
Point taken. Thanks for the tip. Newer to git so the nudge will help.

Cheers

**Comment by persson** [comment]
@damclarkd, I actually deleted my comment from here and created a new issue as I feel like I hijacked your issue.  So we should probably move the discussion of the patch to:
https://github.com/rhodesman/teslaPowerDash/issues/30

Your error may be totally unrelated to my patch.

Regardless, I am interested in finding out if my patch works for others so I can decide if working up a formal PR is worth it.
